---
title: "生物信息学相关"
output: html_document
---

* [Leek, J. T., et al. (2010). "Tackling the widespread and critical impact of batch effects in high-throughput data." Nat Rev Genet 11(10): 733-739.](https://www.nature.com/articles/nrg2825)  
    关于batch effect的经典文献
* [Shafi, A., et al. (2017). "A survey of the approaches for identifying differential methylation using bisulfite sequencing data." Brief Bioinform.](https://academic.oup.com/bib/advance-article/doi/10.1093/bib/bbx013/3064341)  
    比较全面的关于DMRs identification方法的综述
* [Steinhauser, S., et al. (2016). "A comprehensive comparison of tools for differential ChIP-seq analysis." Brief Bioinform 17(6): 953-966](https://academic.oup.com/bib/article/17/6/953/2453197)  
    比较找differential chip peaks的方法综述  
* [Sahraeian, S. M. E., et al. (2017). "Gaining comprehensive biological insight into the transcriptome by performing a broad-spectrum RNA-seq analysis." Nat Commun 8(1): 59.](https://www.nature.com/articles/s41467-017-00050-4)  
    比较RNA-Seq的相关软件和流程总结  
* [Van Den Berge, K., et al. (2019). "RNA sequencing data: hitchhiker's guide to expression analysis."](https://www.annualreviews.org/doi/full/10.1146/annurev-biodatasci-072018-021255)  
    Annual review的RNA-seq综述  
* [Kryuchkova-Mostacci, Nadezda, and Marc Robinson-Rechavi. "A benchmark of gene expression tissue-specificity metrics." Briefings in bioinformatics 18.2 (2017): 205-214.](https://academic.oup.com/bib/article/18/2/205/2562739?login=true)  
    benchmark度量tissue specificity的指标  

## 生物信息课程
* [Bioinformatics Training at the Harvard Chan Bioinformatics Core](https://hbctraining.github.io/main/)
* [2018 bioconductor workshop](https://bioconductor.github.io/BiocWorkshops/)
* [Rafael Irizarry Biomedical Data Science课程](http://genomicsclass.github.io/book/)   [相关视频资料](http://rafalab.github.io/pages/harvardx.html)

## R语言相关
### 入门
* [R Programming for Data Science](https://bookdown.org/rdpeng/rprogdatascience/)  

### 进阶  
* [R for Data Science](https://r4ds.had.co.nz/)  
* [Advanced Statistical Computing](https://bookdown.org/rdpeng/advstatcomp/)  

### 高级  
* [Efficient R programming](https://bookdown.org/csgillespie/efficientR/)  
* [Advanced R](http://adv-r.had.co.nz/)  

## Linux命令行
* [命令行的艺术](https://github.com/jlevy/the-art-of-command-line/blob/master/README-zh.md)

## 统计学相关
### 入门
* 《统计建模与R软件》，作者: 薛毅
* 《统计学习导论:基于R应用》，作者: Gareth James / Daniela Witten / Trevor Hastie